### ISSUE TITLE
Slot timetable changed for chennai campus

### ISSUE THREAD

**Issue by Trevahok** [vatz88/FFCSonTheGo#123]
Slot timetable is changed for Chennai campus. New one can be found here https://github.com/vatz88/FFCSonTheGo/files/3332764/Slot.Timetable.FALL.2018-19.pdf

Change: `TD1` to `TDD1` at the position of `L29`

---

- [x] I have checked that no other similar issue is open or possible closed as `wontfix`

- [X] Please assign me this issue, I would like to work on it.

**Comment by vatz88** [comment]
How much is the difference? We'll need change is architecture to support two different timetables.

**Comment by Trevahok** [comment]
just slight ones … TD1 and TDD1 has changed, i changed the HTML in inspect element and it worked 
[Slot Timetable FALL 2018-19.pdf](https://github.com/vatz88/FFCSonTheGo/files/3332764/Slot.Timetable.FALL.2018-19.pdf)

check out this ….

**Comment by vatz88** [comment]
From what I see, you asking change `TD1` to `TDD1` where `L29` is present, right?

@AnmolTomer can you verify if this change is correct for Chennai?

@sanket9918 I believe the timetable currently used on website is correct for Vellore and there is no change, can you confirm this?

**Comment by AnmolTomer** [comment]
The given reference pdf is of Winter 2018-19, I compared it with General Slot time table on FFCSOnTheGo website. There are minor differences such as what Vellore has as slot V1, Chennai has it as TD1 on Wednesday and similarly for TDD1 in Chennai on Friday what Vellore has as TD1.
![Image with differences marked in Yellow](https://i.imgur.com/9dF7ngB.png) as pointed out by @Trevahok .
Other than that for second half both the time tables are exactly same.

**Comment by sanket9918** [comment]
It can be confirmed that till now some hundreds of the time table are already made and there is not a single issues in any of the timetable slot for Vellore Campus

I can confirm that the timetable slots are working fine.

**Comment by vatz88** [comment]
@sanket9918 what I'm asking is, timetable used by us matches exactly with the official VIT timetable right?

@AnmolTomer how much of an issue this difference is?

**Comment by sanket9918** [comment]
@vatz88 our timetable is exactly matching the university timetable

**Comment by vatz88** [comment]
@Trevahok @AnmolTomer @sanket9918 Do any of you guys want to pick it up? We need to fix this in such a way that we don't break anything for Vellore.

**Comment by Trevahok** [comment]
I will look into the currrent codebase and tell you if i can do this … is that fine?

**Comment by vatz88** [comment]
@Trevahok sure. Even @AnmolTomer is looking into it too.

**Comment by AnmolTomer** [comment]
Can be closed successfully @vatz88 . Had no issues last time, nothing of that sort for this time as well.
