### ISSUE TITLE
Add support for VIT AP campus

### ISSUE THREAD

**Issue by ashua4488** [vatz88/FFCSonTheGo#124]
HOW ABOUT CREATING SIMILAR FUNCTIONALITY FOR FFCS AP CAMPUS. THOSE GUYS ARE REALLY STRUGGLING.

**Comment by AnmolTomer** [comment]
It just needs a similar excel file as we have for Vellore and Chennai campus. Check it out inside the util directory in the master branch of the repo. They have to make that and that would be a good start.

**Comment by ashua4488** [comment]
Yeah, they have all the slots and subjects in the excel sheet, but they
don't have the faculty and classrooms may be they should take the
screenshots while mock registration.
Actually, my brother is studying in AP. I created the timetable for him.


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
07/02/19,
10:54:12 AM

**Comment by AnantGupta001** [comment]
2nd sem CSE subject + faculty + slot list

[CHY1009.pdf](https://github.com/vatz88/FFCSonTheGo/files/10711248/CHY1009.pdf)
[CSE2005.pdf](https://github.com/vatz88/FFCSonTheGo/files/10711250/CSE2005.pdf)
[ECE1003.pdf](https://github.com/vatz88/FFCSonTheGo/files/10711251/ECE1003.pdf)
[ENG1002.pdf](https://github.com/vatz88/FFCSonTheGo/files/10711252/ENG1002.pdf)
[ENG2001.pdf](https://github.com/vatz88/FFCSonTheGo/files/10711254/ENG2001.pdf)
[MAT1002.pdf](https://github.com/vatz88/FFCSonTheGo/files/10711255/MAT1002.pdf)
[PHY1008.pdf](https://github.com/vatz88/FFCSonTheGo/files/10711256/PHY1008.pdf)

**Comment by AnantGupta001** [comment]
Hello @AnmolTomer,

I have written the code for the VIT-AP campus in my local repository. However, we do not receive faculty names in our annexure PDF during course registration, as seen in the example PDF I have uploaded. Could you please advise on how to obtain the faculty names, or should I list them as Faculty-1, Faculty-2, Faculty-3 sequentially?

Thank you.

[ANNEXURE-II(A) Theory Slots.pdf](https://github.com/user-attachments/files/15980667/ANNEXURE-II.A.Theory.Slots.pdf)
[ANNEXURE-II(B) Lab Slots.pdf](https://github.com/user-attachments/files/15980665/ANNEXURE-II.B.Lab.Slots.pdf)

**Comment by therealsujitk** [comment]
@AnantGupta001, for now we can try testing it leaving the field blank. You'll need to make a single `.xlsx` file with the required columns (mentioned here --> https://github.com/vatz88/FFCSonTheGo/blob/master/util/README.md). The values for the columns that you do not have (like faculty) can be left blank.

**Comment by AnantGupta001** [comment]
Hi @therealsujitk,

I am currently working on the project and would like to formally request to be assigned this task. I believe my skills and experience align well with the requirements, and I am confident in my ability to contribute effectively.

Thank you for considering my request.

Best regards,  
Anant Gupta

**Comment by therealsujitk** [comment]
Sure @AnantGupta001! Thankyou for contributing, let me know if you need any help.
