### ISSUE TITLE
Sort not working

### ISSUE THREAD

**Issue by nobi1007** [vatz88/FFCSonTheGo#142]
**Describe the bug**
Not able to sort the selected courses based on the available headers, i.e., slot, course code, title etc.

**To Reproduce**
1. Select some courses, i.e., add some courses to your timetable
2. Click on Slot or code or any other table header

**Expected behavior**
After clicking on any table header the contents should be sorted accordingly, descending or ascending based on the arrow up or down.

**Screenshots**
![image](https://user-images.githubusercontent.com/30571441/86429906-76e2fa80-bd0e-11ea-89b4-5194b17996a3.png)
![image](https://user-images.githubusercontent.com/30571441/86429955-a265e500-bd0e-11ea-91ce-620e32818383.png)

**Comment by nobi1007** [comment]
is it fixed or need improvement?

**Comment by vatz88** [comment]
It is not fixed. If anyone wants, they can pick it up and submit a PR.
