### ISSUE TITLE
Faculty List Not Yet Updated 

### ISSUE THREAD

**Issue by SamPrinceFranklin** [vatz88/FFCSonTheGo#175]
Well for the Chennai Campus some Courses are missing for MTech Integrated Software Engineering and some faculty name list are not yet updated! |

Anyway that can be done to update? I have some data regarding faculty list and courses.

**Comment by vatz88** [comment]
Hey, if you can provide all the data in the format in this excel https://github.com/vatz88/FFCSonTheGo/blob/master/util/report_chennai.xlsx we can update it.

**Comment by vatz88** [comment]
@SamPrinceFranklin can you verify this https://github.com/vatz88/FFCSonTheGo/pull/170 It seems to have updated the course list. I'll merge it after verifying

**Comment by vatz88** [comment]
https://github.com/vatz88/FFCSonTheGo/pull/185 should have fixed it
