### ISSUE TITLE
CSE2006 Microprocessor and Interfacing not available

### ISSUE THREAD

**Issue by namitgpta** [vatz88/FFCSonTheGo#178]
**Describe the bug**
CSE2006 Microprocessor and Interfacing not available on your website. Please add it along with the faculty list.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vatz88** [comment]
https://github.com/vatz88/FFCSonTheGo/pull/185 this should have fixed it
