### ISSUE TITLE
Fall Semester 2021

### ISSUE THREAD

**Issue by shuklasaharsh** [vatz88/FFCSonTheGo#182]
# Fall Semester 2021

### It's that time of the year peeps.

**Comment by vatz88** [comment]
YESSS! Do you have the course allocation report?

**Comment by CrypticMuze** [comment]
> YESSS! Do you have the course allocation report?

docs.google.com/spreadsheets/d/19rOSY6HZlaF_BL9PkI6DQL9T2z57tGKn4jLnyzMCs7A/edit#gid=1506103244
