### ISSUE TITLE
Update contributing guidelines

### ISSUE THREAD

**Issue by therealsujitk** [vatz88/FFCSonTheGo#195]
The [`CONTRIBUTING.md`](https://github.com/vatz88/FFCSonTheGo/blob/master/.github/CONTRIBUTING.md) file needs to be updated to make contributing easier for people looking to contribute for the first time.

It should include,
- [ ]  Steps to install this application locally.
- [ ] What to do before you start working on an issue, opening an issue or requesting a feature.
- [ ] Where to look for code or add new code.
- [ ] Naming scheme and rules to follow while coding.

**Comment by AnantGupta001** [comment]
Hey @therealsujitk,  could you please assign me this task?
