### ISSUE TITLE
Update the website for Winter semester 2021-22

### ISSUE THREAD

**Issue by Abhishek911cse** [vatz88/FFCSonTheGo#203]
I've attached the course allocation report. Please update the website with these new courses. Thanks!

---
[Winter Semester 2021-22 _ Course Allocation Report.pdf](https://github.com/vatz88/FFCSonTheGo/files/7638605/Winter.Semester.2021-22._.Course.Allocation.Report.pdf)

**Comment by Hsad1644** [comment]
[Winter Semester 2021-22 _ Course Allocation Report-converted.xlsx](https://github.com/vatz88/FFCSonTheGo/files/7639244/Winter.Semester.2021-22._.Course.Allocation.Report-converted.xlsx)

Excel template attached above please review and update!

**Comment by vatz88** [comment]
Updated with #205
