### ISSUE TITLE
Total No of credits

### ISSUE THREAD

**Issue by Tharun-PS** [vatz88/FFCSonTheGo#207]
**Describe the bug**
1. The credits column doesn't show up the equivalent credits for the component registered.
2. The total number of credits is not getting updated when user is adding courses to his/her panel

**To Reproduce**
1. Go to course panel and search for course
2. Click on any available course and select 'Add course'
3. Scroll down to see Registered courses and the Total number of credits registered

**Expected behavior**
1. The registered courses table should show the number of credits for respective components in its "Credits" column. But nothing is visible
2. At the bottom of the table, the total number of credits registered should be visible. But the application always shows 0 credits

**Screenshots**
![image](https://user-images.githubusercontent.com/71878525/145666661-2e11e61e-b86b-493e-9fb5-14061941b224.png)
![phone](https://user-images.githubusercontent.com/71878525/145666938-120d7050-cde9-461a-b32b-555b85521600.jpeg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Edge
 - Version EDGE 96.0.1054.43 (Official build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: Redmi Note 5 pro
 - OS: Android 9, MIUI 11.0.5
 - Browser : Google Chrome
 - Version : Chrome 96.0.4664.92

**Additional context**
Checking the equivalent credits and number of credits registered is a very frequent action from user. As it FFCS time, the bug needs to be resolved as soon and possible.

**Comment by vatz88** [comment]
This isn't a bug, we don't have the credits data to show here.
