### ISSUE TITLE
Filter courses by free and paid on Learndash)

### ISSUE THREAD

**Issue by parthvaghela19** [vatz88/FFCSonTheGo#215]
I need to add one filter like dropdown for free course and paid course and also include age wise dropdown (for ex. 5 grade to 10 grade student)  

I am using wordpress, Learndash LMS plugin, BuddyBoss theme
#215 

![Courses](https://user-images.githubusercontent.com/99802104/162419791-dcb0ce3a-159f-4cca-8c99-fd4e022c7d17.PNG)

**Comment by therealsujitk** [comment]
@parthvaghela19 your question doesn't seem to have anything to do with this project or any of it's technologies. You'll be better off asking questions like this on StackOverflow or other similar sites.
