### ISSUE TITLE
Migrate to Google Analytics 4

### ISSUE THREAD

**Issue by therealsujitk** [vatz88/FFCSonTheGo#217]
> Universal Analytics will no longer process new data in standard properties beginning 1 July 2023. Prepare now by setting up and switching over to a Google Analytics 4 property. - [Source](https://support.google.com/analytics/answer/11583528)

@vatz88 looks like we'll have to migrate before 1 July 2023. There's still a lot of time so it's not urgent.

### Links

- [Version check](https://support.google.com/analytics/answer/11583832) - According to this we are currently using Universal Analytics
- [Meet the next generation of Google Analytics](https://support.google.com/analytics/answer/10089681)

**Comment by vatz88** [comment]
Seems google did the migration for us 🥲 
<img width="1496" alt="image" src="https://github.com/vatz88/FFCSonTheGo/assets/16202323/5e0acfb0-bc0e-4619-a6f0-caaa4c074eaf">
