### ISSUE TITLE
Winter Semester 2022-23

### ISSUE THREAD

**Issue by SuyogKhanal** [vatz88/FFCSonTheGo#226]
Please make the website updated for the Winter semester of 2022-23.

**Comment by therealsujitk** [comment]
@SuyogKhanal is this for the Vellore campus? Do you have the course allocation list with you?

**Comment by SuyogKhanal** [comment]
Yes, this is for the Vellore campus, I don't have the course allocation list.

**Comment by therealsujitk** [comment]
Will be closing this as out-dated.
