### ISSUE TITLE
Unsupported Build Image Ubuntu 16.04

### ISSUE THREAD

**Issue by therealsujitk** [vatz88/FFCSonTheGo#231]
@vatz88, deploy builds are failing because the site is currently set to build on Ubuntu 16.04. Can you upgrade this to one of the newer build images?

<img width="1161" alt="Screenshot 2023-10-31 at 01 46 40" src="https://github.com/vatz88/FFCSonTheGo/assets/60378235/87bd9070-a063-4d99-80e1-33460fec5050">

**Comment by vatz88** [comment]
Updated 
<img width="758" alt="image" src="https://github.com/vatz88/FFCSonTheGo/assets/16202323/76920caf-977f-485f-922f-0773f588fb0c">

**Comment by vatz88** [comment]
We also need to upgrade our node version, but that's a different task. Most likely everything will work fine with new node version but need to check.

<img width="908" alt="image" src="https://github.com/vatz88/FFCSonTheGo/assets/16202323/8d2b01ad-3510-49c7-9d2d-47da2ce1968d">

**Comment by therealsujitk** [comment]
Well test and create a PR soon.

**Comment by therealsujitk** [comment]
Looks like builds are working now, so I'll close this as completed.
