### ISSUE TITLE
Load course data if it exists

### ISSUE THREAD

**Issue by sangeeth96** [VaTz88/FFCSonTheGo#36]
## Current Issue
Previous course allocation is still there and currently manual removal is the proposed solution.

## Possible Workaround
1. Try to load the data via an AJAX call and if it fails, prevent initialization of autocomplete.
2. Add a flag variable to determine whether to initialize autocomplete or not. No. 1 solution is basically no work other than updating the manifest I guess.

**Comment by VaTz88** [comment]
resolved in https://github.com/VaTz88/FFCSonTheGo/commit/8a6f4663c63a95a61dfb3282ba102dc48e7ed8a8
