### ISSUE TITLE
Update course list to match the latest allocation report

### ISSUE THREAD

**Issue by sangeeth96** [vatz88/FFCSonTheGo#59]
Allocation report is available [here](https://1drv.ms/x/s!AhAoqL948GhrhsUxrYMDBIF1Q3oB1A). The format is `.xlsx` and that needs to be converted to JSON format and the data extracted to the following files:

- `data\all_data.json` — Should contain all the courses. Format can be referred from the existing version of this file.
- `data\unique_courses.json` — Should consist of only unique course details, i.e, `{ CODE, TITLE }`.

**Comment by vatz88** [comment]
@sangeeth96 Link to the file is not working.

**Comment by sangeeth96** [comment]
Updated.

**Comment by vatz88** [comment]
Well still not working but got it from a WhatsApp group, someone had uploaded it there ;)

![screenshot from 2017-10-25 22-31-45](https://user-images.githubusercontent.com/16202323/32012057-549107f0-b9d4-11e7-9c7c-8696a89cd2e8.png)
