### ISSUE TITLE
New course allocation report in vtopbeta

### ISSUE THREAD

**Issue by sangeeth96** [vatz88/FFCSonTheGo#62]
PDF can be found in vtopbeta. Running through export to Excel in Acrobat yields the excel doc [attached here](https://1drv.ms/x/s!AhAoqL948GhrhsUy8Z-ZhQQ5vFy0kA). Note that the excel document has column headers appearing for each page so the JSON parser needs to account for that.

![image](https://user-images.githubusercontent.com/2759499/32036854-026419ce-ba40-11e7-89eb-0b23c161b750.png)

**Comment by amolmishra23** [comment]
Removed all the headers.
https://drive.google.com/file/d/0B5XvmmV9gfyZQ0RDcmxnZlZkSjA/view?usp=sharing

**Comment by vatz88** [comment]
@amolmishra23 thanks! I'll update the site by tonight.

**Comment by vatz88** [comment]
Done :+1:
