### ISSUE TITLE
Theory and Project Clash for CAL courses

### ISSUE THREAD

**Issue by Shivam60** [vatz88/FFCSonTheGo#63]
when we add a subject, only its theory credits are added not lab or project.
Further **if we add project than it shows it in red meaning it is clashing** when it is not

**Comment by vatz88** [comment]
The course report excel has multiple columns, I'm only considering the last column `Credits`.

**Comment by vatz88** [comment]
Credits total seems kinda confusing but clash between theory and project should be fixed.
@sangeeth96 how about we consider `Project` column for credit totaling but don't add it to timetable to avoid clashing?

JSON data has to be modified for that to get correct credits for project and while adding course to the timetable ignore all `EPJ`

**Comment by sangeeth96** [comment]
![image](https://user-images.githubusercontent.com/2759499/32099893-cc2cd512-bb2f-11e7-9c04-10d319f9e872.png)
Well, what I was thinking was while making the JSON, combine ETH+ELA+EPJ to one subject for each faculty. This is valid based on what I've heard. You have to take the same faculty for each of these so there's no point in separately displaying them in the panel.

Basically, if a subject has ETH+ELA, we'll combine them to one with the type ETH+ELA. As for the credits, the total credits is the sum total of all ETH+ELA+EPJ credits so I don't understand why you'd consider the Project column?

**Comment by vatz88** [comment]
> combine ETH+ELA+EPJ to one subject for each faculty

this can be done if we get the confirmation that students can not take different faculty for different components of same course.

> why you'd consider the Project column?

Well I thought `EPJ` has 0 in CREDITS fields and that is causing not counting of it. But if that's not the case credits total has no issues right?

**Comment by vatz88** [comment]
Also before combining we have to take care that it doesn't mess up the Non-CAL courses. AFAIK Non-CAL has no such restrictions about same faculty.

**Comment by sangeeth96** [comment]
I just tried something with a few assumptions and those didn't work. EPJ has 1 credit and the _Credits_ column values are proper. Current plan to create the JSON file is as follows:
1. Read the entire xls and convert it to JSON.
2. Filter the array of courses to two different arrays — `projectCourses` and `nonProjectCourses`.
3. Iterate through `projectCourses` and find the matching `nonProjectCourse`.
4. Combine the credits and `'EPJ'` string of the `projectCourse` to the matching `nonProjectCourse`.
5. Repeat steps 3 and 4 for every J component course.

**Comment by vatz88** [comment]
Dude that's so damn confusing!

**Comment by vatz88** [comment]
@sangeeth96 what we do next? Let it be what it is?
