### ISSUE TITLE
Feature: Allow sorting of columns in course list

### ISSUE THREAD

**Issue by sangeeth96** [vatz88/FFCSonTheGo#72]
![image](https://user-images.githubusercontent.com/2759499/32123432-c532738c-bb81-11e7-9609-1d2dcd9ed392.png)

This has been a requested feature and we'd love it if someone could help add this feature to the site. User should basically be able to click on the headers of the course list (`#courseListTable`) to sort the entire table by that column. This'd make it easy for someone to see the courses that takes up most credits or group courses by course code and more.

## Features that need to be preserved
1. Double-clicking the row should delete the course.
2. `x` button should be present on the right end of a row to delete the course.

## Suggestions
[DataTables ](https://datatables.net/)comes to my mind. It shouldn't be hard but you might need to refer the manual because direct DOM manipulation with DataTables might break it.

If you are interested to work on this, please leave a comment below.

**Comment by aerohitk** [comment]
@sangeeth96 @vatz88 would it be alright if I worked on this?

**Comment by vatz88** [comment]
Sure @aerohitk I'll assign it to you!

**Comment by vatz88** [comment]
@aerohitk sure you can work on it.

**Comment by aerohitk** [comment]
@vatz88 created the pr here #78. I attempted to go with the suggestion of using DataTables, but that was impossible to do without changing the way you currently add and remove rows. So, instead of rewriting existing infrastructure, I just added the code that would do the sorting. Plus, that saves a network request.

**Comment by vatz88** [comment]
@aerohitk thanks for the PR! I'll look into it.
@sangeeth96 review the PR.
