### ISSUE TITLE
Bug: Lab and theory timings need to be considered to decide clashes

### ISSUE THREAD

**Issue by sangeeth96** [vatz88/FFCSonTheGo#74]
Adjacent lab and theory slot timings need to be considered for the Winter Semester 2018 course registration to decide whether a clash occurred or not. Overlapping slots is not the only condition for a clash to occur.

For example, say I took labs in L59+L60 and I want to take F2+TF2. Right now, this is allowed as none of these slots overlap the other. However, as per the latest rules, this should clash. L59 starts at 05:31 PM while TF2 ends at 05:50 PM. Hence, one can't take both of these slots at the same time.

---

- [x] I have checked that no other similar issue is open or possible closed as `wontfix`

- [ ] Please assign me this issue, I would like to work on it.

**Comment by divyam28** [comment]
Put logic for all of them manually for the time being. For eg. If a student has TB1 AND L5 throw some error. I know doing it manually seems very laboursome but for the time being it will be pretty helpful to a lot of people! Hope it helps.

**Comment by vatz88** [comment]
@divyam28 Thanks for the suggestion. The issue is open for anyone to take up. I'll see if I get time for it.
