### ISSUE TITLE
Incorrect slot gets selected on adding slot through `Add Course` input

### ISSUE THREAD

**Issue by VaTz88** [VaTz88/FFCSonTheGo#8]
Adding slot `A1` from input in `Add Course` selects slot `L42` on timetable.

![bug image](https://cloud.githubusercontent.com/assets/16202323/21263205/80164ec2-c3bb-11e6-87f1-b782d74f8d49.png)

**Comment by sangeeth96** [comment]
Gawd! This thing changed again? :rage: Then the current logic would totally fail cause it's all based on that generated array. Such a drag!

**Comment by VaTz88** [comment]
Don't know what logic you have used but do you mean this problem is because i added saturday and sunday and two extra slots at the end of each day?
If saturday, sunday and extra slots are not required during course registration we can remove it.
But i would say use some different logic. Using classes might work better.

**Comment by sangeeth96** [comment]
Not, not that. Last two columns have different ordering. Currently, there is a `labArray[]` which handles lab + theory slots but now that the ordering is mixed, can't use it anymore. Yep, it'd be quite easier to use classes I agree. I still am not feeling the heat to start working so see if you can come up with something. Create a new branch and work on it I guess.

**Comment by VaTz88** [comment]
I'll leave it to you. Btw i'm not sure if to keep Sat, Sun and 2 extra cols. I think it's not required. I'll remove it later after proper confirmation. You can fix it after that.

**Comment by sangeeth96** [comment]
Okie dokie. :+1:

**Comment by sangeeth96** [comment]
Please see #10. I think I've managed to get it working again but test out just in case. Haven't tested on mobile devices though Chrome renders fine when in devices mode.
