### ISSUE TITLE
New course allocation report available

### ISSUE THREAD

**Issue by vteja711** [vatz88/FFCSonTheGo#82]
Here is the new one. Hope you update it soon.

[Fall 2018-19 Course Offered List.pdf](https://github.com/vatz88/FFCSonTheGo/files/2129776/Fall.2018-19.Course.Offered.List.pdf)

**Comment by vteja711** [comment]
I just uploaded the json file here. It's zipped but I hope this helps.
[courseallocjson.zip](https://github.com/vatz88/FFCSonTheGo/files/2129828/courseallocjson.zip)

**Comment by vatz88** [comment]
@vteja711 Thanks but this json is not in expected format. Check the [README](https://github.com/vatz88/FFCSonTheGo/tree/master/util) file in util folder. Also from next time onwards, if possible just update the json and create a PR straight away!
